### PR TITLE
Create Contact endpoint

### PR DESCRIPTION
**Pull request by NrdyBhu1**

### CODE REVIEW

**Comment by NrdyBhu1** [comment]
Everything looks good, so merging it

**Comment by Nalin-Angrish** [comment]
Cool 👍🏻 Now for some time you might receive some spam emails which i would send for testing so, sorry for disturbance.

**Comment by NrdyBhu1** [comment]
Wait, I didn't push to heroku lol

**Comment by Nalin-Angrish** [comment]
Didn't you configure auto deploy?

**Comment by NrdyBhu1** [comment]
How do you do that?

**Comment by Nalin-Angrish** [comment]
Go to your heroku app's dashboard, then to the deploy tab, Select GitHub in the deployment method and authenticate your github account. Then find your repository, select it, then click enable automatic deploys after selecting the main branch. Also manually deploy the main branch by clicking the deploy branch button in the manual deploy section.

**Comment by NrdyBhu1** [comment]
I never knew all this stuff, thanks added it, its building, also another commit is to be pending so opening pr

**Comment by Nalin-Angrish** [comment]
Okay

**Pull request merged**
